### ISSUE TITLE
unskip and fix mysteriously failing directory test

### ISSUE THREAD

**Issue by TimDaub** [music-os/music-os-core#31]
https://github.com/music-os/music-os-core/blob/170fadfdcd2389eb4fa5e66ad51698f2fa582fe9/test/disc_test.mjs#L19

**Comment by naiknareshh** [comment]
**unlink()** is used to delete a file, to remove an empty folder we will have to use **rmdir()**

```javascript
try {
    await unlink(nonExistentDir);
  } catch (err) {
    console.error(err);
    t.fail();
  }
```

This test passes if we use **rmdir()** , let me know if you have any suggestions.

**Comment by TimDaub** [comment]
> **unlink()** is used to delete a file, to remove an empty folder we will have to use **rmdir()**

Oh awesome, I wasn't aware of this. Thanks for helping out. @naiknareshh, are you interested in sending a PR?
